config/routes.rb
Rails.application.routes.draw do
  resource :users
  resources :favorite_cities
  root 'users#new'


  get '/login' => 'sessions#new', as: 'login'
  get 'users/index'  => 'users#index', as: "dashboard"
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
end

app/models/favorite_city.rb
class FavoriteCity < ApplicationRecord
  belongs_to :user
  geocoded_by :city_name do |object, results|
    if results.present?
      object.latitude = results.first.latitude
      object.longitude = results.first.longitude
    else
      object.latitude = nil
      object.longitude = nil
    end
  end
  validates :city_name, presence: true
  validate :address_presence_and_founded
  before_validation :geocode
  def address_presence_and_founded
    if latitude.blank? || longitude.blank?
      errors.add(:city_name, "We couldn't find the city you are looking for")
      end
    end
  end

app/models/weather_api.rb
class WeatherApi
  include HTTParty

  def self.get_weather(city_name, unit)
    url = "http://api.openweathermap.org/data/2.5/weather?q=#{city_name}&units=#{unit == 'f' ? 'imperial' : 'metric'}&APPID=bfdede37a867d92c2fdf92eda5f6ab7c"
    @response = HTTParty.get(url)
    weather_conditions= @response.body
    return JSON.parse(weather_conditions)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find_by(id:  session[:user_id])
    end

      helper_method :current_user

    def require_logged_in
     if current_user
       true
     else
      redirect_to dashboard_path
    end
  end
end

app/controllers/favorite_cities_controller.rb
class FavoriteCitiesController < ApplicationController
  def new
    @favorite = FavoriteCity.new
  end

  def create
    @favorite = current_user.favorite_cities.build(favorite_params)
    if @favorite.save
      redirect_to dashboard_path, notice: 'Favorite city saved'
    else
      render :new
    end
  end

  def show
    @favorite_city = current_user.favorite_cities.find(params[:id])
    @unit = params[:unit].present? ? params[:unit] : 'C'
    @current_weather = WeatherApi.get_weather(@favorite_city.city_name, @unit)
  end

  def destroy
    @favorite_city = current_user.favorite_cities.find(params[:id])
    @favorite_city.destroy!
    redirect_to dashboard_path, notice: "Favorite city deleted"
  end

  private
  def favorite_params
    params.require(:favorite_city).permit(:city_name, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: params[:email])
    if @user and @user.authenticate(params[:password])
      #logged in
      session[:user_id] = @user.id
      redirect_to dashboard_path, notice: 'You have succesfully logged in.'
    else
      flash[:notice]= "Something was wrong please try again."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'You have succesfully logout.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user= User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path, notice: 'You have succesfully sign up.'
    else
      flash[:notice] = "Please check that your passwords match."
      render :new
    end
  end

  private
  def allowed_params
    params.require(:user).permit(:name, :email, :password, :password_digest, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_cities_helper.rb
module FavoriteCitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorite_cities/new.html.erb
<div class="container favorite">
  <div class="col-sm-8 col-md-6">
    <div class="thumbnail">
      <div class="caption">
        <h1>Add City</h1>
        <% @favorite.errors.full_messages.each do |e| %>
        <p class='errors'><%=  e %></p>
        <%end%>
        <%= form_for(@favorite) do |f|%>
        <%= f.label :city_name, "City Name:" %>
        <%= f.text_field :city_name, id: :city %>
        <%= f.submit 'Add Favorite City', class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorite_cities/show.html.erb
<div class="container favorite show-fav">
  <div class="col-sm-8 col-lg-6">
    <div class="thumbnail">
      <strong>
        <h4>
          <%= link_to favorite_city_path(@favorite_city, unit: (@unit == 'f' ? 'c' : 'f')) do%>
            Change to
            <strong>&#176;<%= "#{@unit.downcase == 'f' ? 'C' : 'F'}" %></strong>
          <%end%>
        </h4>
      </strong>
      <div class="caption">
        <% cache([@favorite_city, 
        @unit], expires_in: 1.minutes ) do %>
          <h1><%= @favorite_city.city_name %></h1>
          <% weather_png = ('http://openweathermap.org/img/w/' + @current_weather['weather'][0]['icon'] + '.png') %>
          <%= image_tag weather_png, class:"png" %>

          <h3> <%= @current_weather["weather"][0]["description"].capitalize!%> </h3>

          <h3> Main:</h3> <h4><%= @current_weather["weather"][0]["main"]%> </h4>

          <h3> Current temperature: </h3>
          <h4> <%= @current_weather["main"]["temp"].round %>
            &#176;<%=@unit.upcase%>
          </h4>

          <h3> Min temperature: </h3> <h4> <%= @current_weather["main"]["temp_min"].round %> &#176;<%=@unit.upcase%></h4>

          <h3> Max temperature:</h3> <h4> <%= @current_weather["main"]["temp_max"].round %> &#176;<%=@unit.upcase%></h4>

          <h3> Humidity: </h3> <h4> <%= @current_weather["main"]["humidity"]%> %  </h4>

          <h3> Wind speed: </h3> <h4><%= @current_weather["wind"]["speed"]%></h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body>


  <nav class="navbar navbar-default nav-bar">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Weather Adviser</a>
      </div>

      <!-- Collect the nav links, forms -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right ">
          <% if current_user %>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'Add a city',  new_favorite_city_path %></li>
          <li><%= link_to 'Logout', logout_path %></li>
          <% else %>
          <li> <%= link_to 'Sign Up', root_path %></li>
          <li ><%= link_to "Log In", login_path %></li>
          <% end %>

          </ul>
        <!-- <form class="navbar-form navbar-right">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Add a Favorite City">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<div class="notice"><%= flash[:notice] %></div>

<h2 class="welcome">Welcome <%= current_user.name.capitalize %></h2>
<% current_user.favorite_cities.each do |favorite_city| %>
<div>
  <div class="col-sm-6 col-md-4 ">
    <div class="thumbnail">
      <div class="caption cities-index">
        <h1><%= link_to favorite_city.city_name, favorite_city_path(favorite_city.id) %></h1>

        <% cache(favorite_city,expires_in: 1.minutes) do %>
        <h3><%=WeatherApi.get_weather(favorite_city.city_name, @unit)["main"]["temp"].round  %>&#8451;</h3>
        <% end %>

        <p><%= link_to 'Delete', favorite_city_path(favorite_city.id), :method => :delete, data: {:confirm => "You sure?"} ,:title => "Delete #{favorite_city.city_name}", class:"btn btn-default"%></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="registration-sign-up">
    <div class="notice"><%= flash[:notice] %></div>
    <h1>Sign Up</h1>
    <%= form_with(model: @user, url: users_path(@user)) do |f| %>

    <div class="box">
      <div class="form-group row ">
        <span class="col-sm-2 col-form-label inputs-sign-up">
          <%= f.label :name %>
          <%= f.text_field :name, id: :Name %>
        </span>
      </div>

      <div class="form-group row ">
        <span class="col-sm-1 col-form-label inputs-sign-up">
          <%= f.label :email %>
          <%= f.text_field :email , id: :Email %>
        </span>
      </div>

      <div class="form-group row ">
        <span class="col-sm-2 col-form-label inputs-sign-up">
          <%= f.label  :password %>
          <%= f.password_field :password, id: :Password%>
        </span>
      </div>

      <div class="form-group row ">
        <span class="col-sm-2 col-form-label inputs-sign-up">  <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation , id: :Password_confirmation %>
        </span>
      </div>

      <p class="button">
        <%= f.submit "Sign Up",  class: "btn btn-primary" %>
      </p>
      <% end %>
    </div>
  </div>
</div>